# theme: tokyo-night-alpha-tmux
Highlights:
      - name: BORDER_HEX
        hex:  "#3b4261"
        ansi: "\e[38;2;59;66;97m"
      - name: BG_HEX
        hex:  "#24283b"
        ansi: "\e[48;2;36;40;59m"
      - name: HEADER_HEX
        hex:  "#7aa2f7"
        ansi: "\e[38;2;122;162;247m"
      - name: TEXT_HEX
        hex:  "#c0caf5"
        ansi: "\e[38;2;192;202;245m"
      - name: HEADERC
        hex:  "#7aa2f7"
        ansi: "\e[38;2;122;162;247m"
      - name: MENUKEYC
        hex:  "#e0af68"
        ansi: "\e[38;2;224;175;104m"
      - name: TAGLINEC
        hex:  "#7dcfff"
        ansi: "\e[38;2;125;207;255m"
      - name: BORDERC
        hex:  "#3b4261"
        ansi: "\e[38;2;59;66;97m"
      - name: BRACKETC
        hex:  "#565f89"
        ansi: "\e[38;2;86;95;137m"
      - name: KEYC
        hex:  "#e0af68"
        ansi: "\e[38;2;224;175;104m"
      - name: TEXTC
        hex:  "#c0caf5"
        ansi: "\e[38;2;192;202;245m"
      - name: ICONC
        hex:  "#7aa2f7"
        ansi: "\e[38;2;122;162;247m"
      - name: BUTTON_BGC
        hex:  "#292e42"
        ansi: "\e[48;2;41;46;66m"
      - name: ACCENTC
        hex:  "#ff9e64"
        ansi: "\e[38;2;255;158;100m"
      - name: PROMPTC
        hex:  "#ff9e64"
        ansi: "\e[38;2;255;158;100m"
