
Profiles:
  - name: "Default"
    theme: "gruvbox-alpha-tmux"
    status: "active"
    configs: "config/settings.yaml"
    projects: "/home/lucifer/Projects/"
    modules:
      - name: "gitgud"
        status: "inactive"
      - name: "alpha_settings"
        status: "active"
