
Profiles:
  - name: "Default"
    status: "active"
    theme: "tokyo-night-alpha-tmux"
    mode: "window"
    configs: "config/settings.yaml"
    projects: "/home/lucifer/Projects/"
    defaultd: "alpha-tmux"
    ai_default: "agy"
    startup: ""
